name: Dev Container

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build dev container
        uses: devcontainers/ci@v0.3
        with:
          configFile: .devcontainer/devcontainer.json
          push: never
